"""add_service_fields_and_landscaping

Revision ID: 037ef7a3d2b2
Revises: 
Create Date: 2026-02-24 09:29:56.058755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '037ef7a3d2b2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # service_start_date and service_frequency were partially applied; add remaining columns
    op.add_column('customers', sa.Column('service_status', sa.String(length=20), nullable=False, server_default='pending'))
    op.add_column('customers', sa.Column('fieldroutes_customer_id', sa.String(length=100), nullable=True))
    op.add_column('customers', sa.Column('fieldroutes_subscription_id', sa.String(length=100), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'fieldroutes_subscription_id')
    op.drop_column('customers', 'fieldroutes_customer_id')
    op.drop_column('customers', 'service_status')
    op.drop_column('customers', 'service_frequency')
    op.drop_column('customers', 'service_start_date')
    # ### end Alembic commands ###
